---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 2.3.7
serverless_language: node
polling_url: https://www.alert.swiss/content/alertswiss-internet/de/home/_jcr_content/polyalert.alertswiss_alerts.actual.json
polling_headers: ''
polling_body: ''
id: 238152
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: author_bio
  field_type: author_bio
  name: About This Plugin
  description: Displays official public warnings from <a href="https://www.alert.swiss/" target="_blank" rel="noopener">Alertswiss</a>. Source code and documentation are available on <a href="https://github.com/michaelkurath/TRMNL-AlertSwiss" target="_blank" rel="noopener">GitHub</a>.
  category: environment,news
  email_address: michael.kurath@gmail.com
  learn_more_url: https://github.com/michaelkurath/TRMNL-AlertSwiss
- keyname: cantons
  field_type: string
  name: Cantons (comma-separated)
  description: 'Choose from which Canton you want alerts. Use CH to show alerts from all cantons. Nationwide alerts are always shown. Example: ZH,SG,SH'
  placeholder: ZH,SG,SH
  default: CH
  optional: true
- keyname: limit
  field_type: number
  name: Max alerts
  description: Maximum number of matching alerts to display
  default: 5
  optional: true
name: Alert.Swiss
description: Swiss alerts by canton
refresh_interval: 60
